# Site settings
title: "Yujian(Ken) He"
email: "easyjiajob@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://kennnnn774.github.io/" # the subpath of your site, e.g. /blog/
url: "https://kennnnn774.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
